import { Consts } from "./types.ts";

const CONSTS: Consts = {
  STARTERS_AFTREK_WAARDE: 2123,
  MKB_VRIJSTELLING_PERCENTAGE: 14,
  ZVW_BIJDRAGE_PERCENTAGE: 5.43,
  ZVW_BIJDRAGE_MAX_BIJDRAGE: 66956,
  ZELFSTANDIGEN_AFTREK_UREN_CRITERIUM: 1225,
  ZELFSTANDIGEN_AFTREK_WAARDE: 5030,
  INKOMSTENBELASTING_SCHIJF_1_MAX: 73031,
  INKOMSTENBELASTING_SCHIJF_1_PERCENTAGE: 36.93,
  INKOMSTENBELASTING_SCHIJF_2_PERCENTAGE: 49.5,
  HEFFINGSKORTING_GRENS1: 22661,
  HEFFINGSKORTING_GRENS2: 73031,
  HEFFINGSKORTING_BEDRAG: 3070,
  HEFFINGSKORTING_PERCENTAGE: 6.095,
  TARIEF_AANPASSING_MAX_WINST: 73031,
  TARIEF_AANPASSING_BELASTBARE_WINST_KORTING_PERCENTAGE: 12.57,
};

export default CONSTS;
